<?php
/**
 * This file is a part of XCRM Core Package
 *
 * @link      https://webwizardry.ru/projects/xcrm
 * @license   https://webwizardry.ru/projects/xcrm/license/
 * @copyright Copyright (c) 2020, Web Wizardry (http://webwizardry.ru)
 */

namespace XCrm\Modules\Reference\BackOffice\Controller;
use XCrm\Data\Controller\CrudController;
use XCrm\Modules\Reference\Model\ReferenceStructure;
use yii\base\Action;
use yii\web\BadRequestHttpException;

class CategoriesController extends CrudController
{
    /**
     * @var string|ReferenceStructure
     */
    public $modelClass = 'reference.structure';

    /**
     * @param Action $action
     * @return bool
     * @throws BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $this->view->headingIcon = 'reference';
        $this->view->heading = static::t('Рубрикатор справочников');

        $this->crumb(\XCrm\Modules\Settings\Module::getTitle(), ['/settings/default/index'], false);
        $this->crumb('Рубрикатор справочников', ['categories/index']);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}