<?php
/**
 * This file is a part of XCRM Core Package
 *
 * @link      https://webwizardry.ru/projects/xcrm
 * @license   https://webwizardry.ru/projects/xcrm/license/
 * @copyright Copyright (c) 2020, Web Wizardry (http://webwizardry.ru)
 */

namespace XCrm\Modules\Reference\BackOffice\Controller;


use XCrm\Data\Controller\CrudController;

class RegistryController extends CrudController
{
    public $modelClass = 'reference.registry';

    public function beforeAction($action)
    {
        $this->view->headingIcon = 'reference';
        $this->view->heading = static::t('Реестр справочников');

        $this->crumb(\XCrm\Modules\Settings\Module::getTitle(), ['/settings/default/index'], false);
        $this->crumb('Реестр справочников', ['registry/index']);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}