<?php
/**
 * This file is a part of XCRM Core Package
 *
 * @link      https://webwizardry.ru/projects/xcrm
 * @license   https://webwizardry.ru/projects/xcrm/license/
 * @copyright Copyright (c) 2020, Web Wizardry (http://webwizardry.ru)
 */

namespace XCrm\Modules\Reference\BackOffice\Controller;
use XCrm\Data\Controller\CrudController;
use XCrm\Modules\Reference\Model\ReferenceRegistry;
use XCrm\Modules\Reference\Model\ReferenceStructure;

class ValuesController extends CrudController
{
    public function beforeAction($action)
    {
        $this->view->headingIcon = 'reference';
        $this->view->heading = static::t('Обзор справочников');

        $this->crumb(\XCrm\Modules\Settings\Module::getTitle(), ['/settings/default/index'], false);
        $this->crumb('Обзор справочников', ['default/index']);

        $ref = ReferenceRegistry::findOne(['uuid' => $this->id]);
        $cat = ReferenceStructure::findOne(['id' => $ref->parent_id]);

        $this->crumb($cat->name, ['default/index', 'category' => $cat->url]);
        $this->crumb($ref->name, ['index']);

        $this->view->heading = $ref->name;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}